source 'https://rubygems.org'

gem 'jekyll', '>= 4.3.2'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets'
  gem 'jekyll_emoji_tag', path: '../'  # use unreleased gem dependencies defined in the parent project
  gem 'jekyll-environment-variables'
  gem 'jekyll-tagging'
end

gem 'debase', '0.2.5.beta2', require: false
gem 'rspec-core', require: false
gem 'rubocop', require: false
gem 'rubocop-rspec', require: false
gem 'ruby-debug-ide', require: false
